name: Build .NET 4.8 App
permissions:
  contents: write
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout dll repo
        run: git clone https://github.com/CrystalMarble/dllrepo
      - name: Copy Ultra dlls
        run: |
          mkdir -Force DevUtils/Libraries
          copy dllrepo/ultra/* DevUtils/Libraries/
      - name: Download 0Harmony
        run: |
          Invoke-WebRequest "https://github.com/pardeike/Harmony/releases/download/v2.3.3.0/Harmony-Fat.2.3.3.0.zip" -OutFile ./_Harmony.zip
          mkdir _Harmony
          Expand-Archive -LiteralPath ./_Harmony.zip -DestinationPath ./_Harmony/
          copy ./_Harmony/net48/0Harmony.dll ./DevUtils/Libraries/
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
        with:
          nuget-version: "latest"

      - name: Build Solution
        run: msbuild ./DevUtils/DevUtils.csproj /p:Configuration=Release
      - name: Copy necessary files to release
        run: |
          mkdir Release
          copy ./DevUtils/bin/Release/DevUtils.* Release/
      - name: Publish Build Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: DevUtils
          path: Release
  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: DevUtils
          path: Release
      - name: ZIPs the contents
        uses: TheDoctor0/zip-release@0.7.1
        with:
          filename: "DevUtils.zip"
          directory: Release
      - name: Create Relese
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "Release/*.zip"
          tag: "${{ github.ref_name }}"
          name: "DevUtils-${{ github.ref_name }}"
